### ISSUE TITLE
Issues in Getting UI

### ISSUE THREAD

**Issue by leosimony** [EoleDev/aker-ui#1]
@EoleDev 
git clone https://github.com/EoleDev/aker-ui.git -- this does the work as usual 

cd aker-ui
git submodule update - as per my understanding this should fetch the repo in "https://github.com/EoleDev/aker-ui-server.git" to sub dir "server" 
^^ This is not happening. Not sure if the issue is on my end.

I am continuing by cloning the server repo manually. I just thought to let you know if this helps to standardize this repo.

**Comment by EoleDev** [comment]
Yes, my bad...
I forgot the command : `git submodule init`
It should be run before `git submodule update`
