### ISSUE TITLE
Blank page when I access UI

### ISSUE THREAD

**Issue by leosimony** [EoleDev/aker-ui#2]
I should create a new issue or open the one already closed. Please let me know and will follow in the future.

PHP Version and modules:
root@ubuntu18-04:/var/www/html/aker-ui# php -v
PHP 7.3.15-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

root@ubuntu18-04:/var/www/html/aker-ui# php -m
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

Composer: 
root@ubuntu18-04:/var/www/html/aker-ui/server# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

When I run the index.php in root directory in cli, got below error.

root@ubuntu18-04:/var/www/html/aker-ui# php index.php
{
    "statusCode": 404,
    "error": {
        "type": "RESOURCE_NOT_FOUND",
        "description": "Not found."
    }
}

When I access the UI in the browser

for ex: http://x.x.x.x/aker-ui/app/
I am getting a blank screen

I tried looking for logs but couldn't find any. 

![Image 406](https://user-images.githubusercontent.com/47471901/75764229-90296980-5d63-11ea-867d-87fbadab4f06.png)

**Comment by EoleDev** [comment]
Hi @leosimony,
When two issues have nothing in common, it is best to open a new one :)

Concerning your issue, you should try to see if it is working when the UI is put on the root of your vhost. so http://192.168.124.223
I didn't test on a subdirectory, and I think there is some changes needed for it to work.

For information, the 404 on the index.php is a normal behavior.

**Comment by leosimony** [comment]
Hello @EoleDev 
Thank you for your immediate reply. 
Yes, it worked from root.

Now, when I try to add user, hostgroups, usergroups, when I click the tick mark, no changes happening and it stays intact. Its not reflected in DB as well.

Am I doing anything wrong?

**Comment by EoleDev** [comment]
Hum, I don't know yet :)
Have you updated the settings ? Your mysql parameters are correct ?
What is the name of your database ?
Did you have a php error ?

**Comment by leosimony** [comment]
Yes, parameters are correct. I have verified in cli.

'database' => [
                'host' => 'localhost',
                'user' => 'aker',
                'password' => 'aker_pass',
                'base' => 'aker'

root@ubuntu18-04:/var/www/html/server# mysql -u aker -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 55
Server version: 10.0.38-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| aker               |
| information_schema |
+--------------------+
2 rows in set (0.00 sec)

I did not have a PHP error and no errors at all in the UI. 

I cannot check the logs in the app directory as there is no log file generated. Tired updating 'displayErrorDetails to true' and still I cannot see any error. 

Has this worked well for you? If so, what is the spec of the base machine you have checked? 

May be missing a module or package?

**Comment by EoleDev** [comment]
Ok!
If you have changed displayErrorDetails to true, you may find some debug info.
In your browser open the inspection tools (F12).
You may find a tab named "network". On this tab you will find all the request sent by your browser.
Try to create a user, and see the request sent. Could you send me the response content ?

**Comment by leosimony** [comment]
@EoleDev Hey, it was a problem with apache which I figured out with your inputs about the inspection tools and **it works great**

Another thing is, I already had few data in the DB and that got pulled in the UI which is awesomely awesome.

I will go over the UI and let you know if any.

**Thanks a ton**

**Comment by EoleDev** [comment]
I am glad all is working well!
For future references, could you explain the problem you had with apache ?

**Comment by leosimony** [comment]
Ah that one, **AllowOverride** will be None by default for the Document root. 
To make the .htaccess active, we need to make it as **AllowOverride All**

**Comment by EoleDev** [comment]
Yes of course!
I will add it the documentation!
Thanks!
